---
deployment:
  tasks:
    - export DEPLOYPATH=/home/user/public_html/
    - /bin/rsync -a --delete --exclude=".git" --exclude=".cpanel.yml" /home/adamwatk/public_html/LAA-Cravings/ $DEPLOYPATH  
    
